"""Invoice_status

Revision ID: 4239845fda08
Revises: aa6710c85cd5
Create Date: 2024-02-04 13:04:29.856346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4239845fda08'
down_revision = 'aa6710c85cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('APPROVED', 'TOKENIZED', 'EARLY_PAYMENT', 'COMPLETED', name='invoicestatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
