"""new

Revision ID: 9e01f9561cc7
Revises: 9e99075e5962
Create Date: 2024-01-31 15:02:58.220933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e01f9561cc7'
down_revision = '9e99075e5962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funded_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('funding_status', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['lender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funding_status')
        batch_op.drop_column('funded_amount')
        batch_op.drop_column('lender_id')

    # ### end Alembic commands ###
