"""Invoice_status3

Revision ID: a679326f9249
Revises: 4239845fda08
Create Date: 2024-02-04 13:22:25.288287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a679326f9249'
down_revision = '4239845fda08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('APPROVED', 'TOKENIZED', 'EARLY_PAYMENT', 'COMPLETED', name='invoicestatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
